// DATA IKAN PULAU 1 (hasil pemulihan: nama & tier utuh, URL gambar hilang -> img: null)
const FISH_DB = [
    // --- COMMON ---
    { tier: "Common", name: "Abyssal Slickhead", img: null },
    { tier: "Common", name: "Anchovy", img: null },
    { tier: "Common", name: "Aqua Scribe", img: null },
    { tier: "Common", name: "Atlantean Anchovy", img: null },
    { tier: "Common", name: "Atlantean Sardine", img: null },
    { tier: "Common", name: "Blisterfish", img: null },
    { tier: "Common", name: "Bluegem Angelfish", img: null },
    { tier: "Common", name: "Bluegill", img: null },
    { tier: "Common", name: "Bluelip Batfish", img: null },
    { tier: "Common", name: "Bream", img: null },
    { tier: "Common", name: "Cardinal Tetra", img: null },
    { tier: "Common", name: "Carrot Goldfish", img: null },
    { tier: "Common", name: "Carrot Pufferfish", img: null },
    { tier: "Common", name: "Cave Loach", img: null },
    { tier: "Common", name: "Chub", img: null },
    { tier: "Common", name: "Cladoselache", img: null },
    { tier: "Common", name: "Clowned Triggerfish", img: null },
    { tier: "Common", name: "Coin Triggerfish", img: null },
    { tier: "Common", name: "Column Crawler", img: null },
    { tier: "Common", name: "Coral Chromis", img: null },
    { tier: "Common", name: "Corsair Grouper", img: null },
    { tier: "Common", name: "Crowned Royal Gramma", img: null },
    { tier: "Common", name: "Cryoskin", img: null },
    { tier: "Common", name: "Deep-sea Dragonfish", img: null },
    { tier: "Common", name: "Deep-sea Hatchetfish", img: null },
    { tier: "Common", name: "Emerald Angelfish", img: null },
    { tier: "Common", name: "Flamekissed Hawkfish", img: null },
    { tier: "Common", name: "Frostscale Fangtooth", img: null },
    { tier: "Common", name: "Gazerfish", img: null },
    { tier: "Common", name: "Gem Anchovy", img: null },
    { tier: "Common", name: "Gem Salmon", img: null },
    { tier: "Common", name: "Glassfish", img: null },
    { tier: "Common", name: "Gloamfin Gar", img: null },
    { tier: "Common", name: "Gloombiter", img: null },
    { tier: "Common", name: "Grayling", img: null },
    { tier: "Common", name: "Green Sea Urchin", img: null },
    { tier: "Common", name: "Gudgeon", img: null },
    { tier: "Common", name: "Haddock", img: null },
    { tier: "Common", name: "Hellfire Haddock", img: null },
    { tier: "Common", name: "Herring", img: null },
    { tier: "Common", name: "Horseshoe Crab", img: null },
    { tier: "Common", name: "Hydra Haddock", img: null },
    { tier: "Common", name: "Inferno Hide", img: null },
    { tier: "Common", name: "Largemouth Bass", img: null },
    { tier: "Common", name: "Leviathan Humpback Anglerfish", img: null },
    { tier: "Common", name: "Lobster", img: null },
    { tier: "Common", name: "Mackerel", img: null },
    { tier: "Common", name: "Mexican Tetra", img: null },
    { tier: "Common", name: "Minnow", img: null },
    { tier: "Common", name: "Moon Arctic Char", img: null },
    { tier: "Common", name: "Moonveil Killifish", img: null },
    { tier: "Common", name: "Mullet", img: null },
    { tier: "Common", name: "Mussel", img: null },
    { tier: "Common", name: "Neon Tetra", img: null },
    { tier: "Common", name: "Neptune’s Nibbler", img: null },
    { tier: "Common", name: "Night Shrimp", img: null },
    { tier: "Common", name: "Oracle Minnow", img: null },
    { tier: "Common", name: "Pearl", img: null },
    { tier: "Common", name: "Perch", img: null },
    { tier: "Common", name: "Piranha", img: null },
    { tier: "Common", name: "Pollock", img: null },
    { tier: "Common", name: "Porgy", img: null },
    { tier: "Common", name: "Poseidon’s Perch", img: null },
    { tier: "Common", name: "Quartzfin Queenfish", img: null },
    { tier: "Common", name: "Red Drum", img: null },
    { tier: "Common", name: "Red Snapper", img: null },
    { tier: "Common", name: "Reef Minnow", img: null },
    { tier: "Common", name: "Sand Dollar", img: null },
    { tier: "Common", name: "Sardine", img: null },
    { tier: "Common", name: "Sea Bass", img: null },
    { tier: "Common", name: "Shortfin Mako Shark", img: null },
    { tier: "Common", name: "Shrimp", img: null },
    { tier: "Common", name: "Silver Scuttler", img: null },
    { tier: "Common", name: "Slate Tuna", img: null },
    { tier: "Common", name: "Smallmouth Bass", img: null },
    { tier: "Common", name: "Sockeye Salmon", img: null },
    { tier: "Common", name: "Sparkfin Tetra", img: null },
    { tier: "Common", name: "Spiderfish", img: null },
    { tier: "Common", name: "Swamp Bass", img: null },
    { tier: "Common", name: "Sweetfish", img: null },
    { tier: "Common", name: "Titanic Black Seadevil", img: null },
    { tier: "Common", name: "Trout", img: null },
    { tier: "Common", name: "Voltfin Carp", img: null },
    { tier: "Common", name: "White Perch", img: null },
    // --- RARE ---
    { tier: "Rare", name: "Abyssacuda", img: null },
    { tier: "Rare", name: "Alligator Gar", img: null },
    { tier: "Rare", name: "Antarctic Icefish", img: null },
    { tier: "Rare", name: "Arapaima", img: null },
    { tier: "Rare", name: "Atlantean Alchemist", img: null },
    { tier: "Rare", name: "Banditfish", img: null },
    { tier: "Rare", name: "Black Dragon Fish", img: null },
    { tier: "Rare", name: "Black Ghost Knifefish", img: null },
    { tier: "Rare", name: "Blue Ribbon Eel", img: null },
    { tier: "Rare", name: "Bluefin Tuna", img: null },
    { tier: "Rare", name: "Carrot Salmon", img: null },
    { tier: "Rare", name: "Catfish", img: null },
    { tier: "Rare", name: "Chillfin Herring", img: null },
    { tier: "Rare", name: "Cobia", img: null },
    { tier: "Rare", name: "Coelacanth", img: null },
    { tier: "Rare", name: "Coin Piranha", img: null },
    { tier: "Rare", name: "King Oyster", img: null },
    { tier: "Rare", name: "Lapisjack", img: null },
    { tier: "Rare", name: "Lightning Pike", img: null },
    { tier: "Rare", name: "Mahi Mahi", img: null },
    { tier: "Rare", name: "Marsh Gar", img: null },
    { tier: "Rare", name: "Massive Marlin", img: null },
    { tier: "Rare", name: "Mauve Pearl", img: null },
    { tier: "Rare", name: "Molten Moray", img: null },
    { tier: "Rare", name: "Mushgrove Crab", img: null },
    { tier: "Rare", name: "Mutated Crystal Shrimp", img: null },
    { tier: "Rare", name: "Napoleonfish", img: null },
    { tier: "Rare", name: "Net Wolffish", img: null },
    { tier: "Rare", name: "Northern Snakehead", img: null },
    { tier: "Rare", name: "Payara", img: null },
    { tier: "Rare", name: "Phanerorhynchus", img: null },
    { tier: "Rare", name: "Prismatic Parrotfish", img: null },
    { tier: "Rare", name: "Pufferfish", img: null },
    { tier: "Rare", name: "Pufferflute", img: null },
    { tier: "Rare", name: "Pyrite Pufferfish", img: null },
    { tier: "Rare", name: "Pyrogrub", img: null },
    { tier: "Rare", name: "Queen Angelfish", img: null },
    { tier: "Rare", name: "Red Fangtooth", img: null },
    { tier: "Rare", name: "Redeye Piranha", img: null },
    { tier: "Rare", name: "Reefrunner Snapper", img: null },
    { tier: "Rare", name: "Ruby Rasbora", img: null },
    { tier: "Rare", name: "Sailfish", img: null },
    { tier: "Rare", name: "Sea Urchin", img: null },
    { tier: "Rare", name: "Shiverfin Haddock", img: null },
    { tier: "Rare", name: "Silver Arowana", img: null },
    { tier: "Rare", name: "Siren Sculpin", img: null },
    { tier: "Rare", name: "Sloane’s Viperfish", img: null },
    { tier: "Rare", name: "Snowfish", img: null },
    { tier: "Rare", name: "Spider Crab", img: null },
    { tier: "Rare", name: "Spiny Hatchetfish", img: null },
    { tier: "Rare", name: "Starbellied Wolf Fish", img: null },
    { tier: "Rare", name: "Starlit Weaver", img: null },
    { tier: "Rare", name: "Stingray", img: null },
    { tier: "Rare", name: "Stormcloud Angelfish", img: null },
    { tier: "Rare", name: "Sturgeon", img: null },
    { tier: "Rare", name: "Suckermouth Catfish", img: null },
    { tier: "Rare", name: "Swordfish", img: null },
    { tier: "Rare", name: "Titanfang Grouper", img: null },
    { tier: "Rare", name: "Titanic Sturgeon", img: null },
    { tier: "Rare", name: "Triton’s Herald", img: null },
    { tier: "Rare", name: "Twilight Glowfish", img: null },
    { tier: "Rare", name: "Typhoon Tuna", img: null },
    { tier: "Rare", name: "Viperfish", img: null },
    { tier: "Rare", name: "Voidfin Mahi", img: null },
    { tier: "Rare", name: "Voidscale Guppy", img: null },
    { tier: "Rare", name: "Volcanic Geode", img: null },
    { tier: "Rare", name: "Warty Frogfish", img: null },
    // --- LEGENDARY ---
    // TODO: ikan tier Legendary belum ada di file asli. Isi di sini.
    // --- MYTHIC ---
    { tier: "Mythic", name: "Abyssal Devourer", img: null },
    { tier: "Mythic", name: "Abyssal Goliath", img: null },
    { tier: "Mythic", name: "Abyssal Grenadier", img: null },
    { tier: "Mythic", name: "Amblypterus", img: null },
    { tier: "Mythic", name: "Atolla Jellyfish", img: null },
    { tier: "Mythic", name: "Aurora Pearl", img: null },
    { tier: "Mythic", name: "Aurora Trout", img: null },
    { tier: "Mythic", name: "Barreleye Fish", img: null },
    { tier: "Mythic", name: "Blisterback Blenny", img: null },
    { tier: "Mythic", name: "Carrot Snapper", img: null },
    { tier: "Mythic", name: "Celestial Koi", img: null },
    { tier: "Mythic", name: "Chasm Leech", img: null },
    { tier: "Mythic", name: "Chillfin Chimaera", img: null },
    { tier: "Mythic", name: "Colossal Squid", img: null },
    { tier: "Mythic", name: "DJ Spinopus", img: null },
    { tier: "Mythic", name: "Electric Blue Seahorse", img: null },
    { tier: "Mythic", name: "Emperor Jellyfish", img: null },
    { tier: "Mythic", name: "Frigid Mammoth Tusk", img: null },
    { tier: "Mythic", name: "Glacial Sturgeon", img: null },
    { tier: "Mythic", name: "Golden Seahorse", img: null },
    { tier: "Mythic", name: "Grand Reef Guardian", img: null },
    { tier: "Mythic", name: "Icebeard Shark", img: null },
    { tier: "Mythic", name: "Inferno Wood", img: null },
    { tier: "Mythic", name: "King Jellyfish", img: null },
    { tier: "Mythic", name: "Meg’s Fang", img: null },
    { tier: "Mythic", name: "Meg’s Spine", img: null },
    { tier: "Mythic", name: "Musical Crab", img: null },
    { tier: "Mythic", name: "Mutated Shark", img: null },
    { tier: "Mythic", name: "Mythic Fish", img: null },
    { tier: "Mythic", name: "Penguin", img: null },
    { tier: "Mythic", name: "Sea Snake", img: null },
    { tier: "Mythic", name: "Shimmering Silverside", img: null },
    { tier: "Mythic", name: "Twilight Tentaclefish", img: null },
    { tier: "Mythic", name: "Void Angler", img: null },
    { tier: "Mythic", name: "Void Emperor", img: null },
    { tier: "Mythic", name: "Voltfish", img: null },
    { tier: "Mythic", name: "Zeus’ Herald", img: null },
    // --- SECRET ---
    { tier: "Secret", name: "Abyssborn Monstrosity", img: null },
    { tier: "Secret", name: "Ancient Kraken", img: null },
    { tier: "Secret", name: "Ancient Orca", img: null },
    { tier: "Secret", name: "Caustic Starwyrm", img: null },
    { tier: "Secret", name: "Colossal Ethereal Dragon", img: null },
    { tier: "Secret", name: "Elder Mossjaw", img: null },
    { tier: "Secret", name: "Gem Blobfish", img: null },
    { tier: "Secret", name: "Great Goldcursed Shark", img: null },
    { tier: "Secret", name: "Manatee", img: null },
    { tier: "Secret", name: "Molten Ripple", img: null },
    { tier: "Secret", name: "Pirate Captain’s Goldfish", img: null },
    { tier: "Secret", name: "Profane Leviathan", img: null },
    { tier: "Secret", name: "Scylla", img: null },
    // --- MEGALODON HUNT ---
    { tier: "Megalodon Hunt", name: "Ancient Megalodon", img: null },
    { tier: "Megalodon Hunt", name: "Megalodon", img: null },
    { tier: "Megalodon Hunt", name: "Phantom Megalodon", img: null },
    // --- KRAKEN HUNT ---
    { tier: "Kraken Hunt", name: "The Kraken", img: null },
];

// DATA PANCINGAN (hasil pemulihan). img & luckLabel hilang; currency ditebak dari harga/ID (1-18 idr, 19+ usd)
const ROD_DATA = [
    { id: 1, name: "Starter Rod", price: 0, currency: "idr", img: null },
    { id: 2, name: "Basic Rod", price: 15000, currency: "idr", img: null },
    { id: 3, name: "Pro Rod", price: 50000, currency: "idr", img: null },
    { id: 4, name: "Advanced Rod", price: 150000, currency: "idr", img: null },
    { id: 5, name: "God Rod", price: 500000, currency: "idr", img: null },
    { id: 6, name: "Divine Rod", price: 1000000, currency: "idr", img: null },
    { id: 7, name: "Transcendent Rod", price: 2500000, currency: "idr", img: null },
    { id: 8, name: "Celestial Rod", price: 5000000, currency: "idr", img: null },
    { id: 9, name: "Void Rod", price: 7500000, currency: "idr", img: null },
    { id: 10, name: "Eternal Rod", price: 10000000, currency: "idr", img: null },
    { id: 11, name: "Hunter Rod", price: 15000000, currency: "idr", img: null },
    { id: 12, name: "Saturn Rod", price: 20000000, currency: "idr", img: null },
    { id: 13, name: "Cosmic Rod", price: 25000000, currency: "idr", img: null },
    { id: 14, name: "Origin Rod", price: 30000000, currency: "idr", img: null },
    { id: 15, name: "Mythic Rod", price: 40000000, currency: "idr", img: null },
    { id: 16, name: "Blossom Rod", price: 50000000, currency: "idr", img: null },
    { id: 17, name: "Cupid Rod", price: 60000000, currency: "idr", img: null },
    { id: 18, name: "Chery Rod", price: 70000000, currency: "idr", img: null },
    { id: 19, name: "Sakura Rod", price: 500, currency: "usd", img: null },
    { id: 20, name: "Omnipotent Rod", price: 1000, currency: "usd", img: null },
    { id: 21, name: "Omniscient Rod", price: 2500, currency: "usd", img: null },
    { id: 22, name: "Omniversal Rod", price: 5000, currency: "usd", img: null },
    { id: 23, name: "Genesis Rod", price: 10000, currency: "usd", img: null },
    { id: 24, name: "???? ???", price: 999999999, currency: "usd", img: null },
];

module.exports = { FISH_DB, ROD_DATA };
