// DATA IKAN PULAU 2 / LUMINESCENT (hasil pemulihan: URL gambar hilang -> img: null)
const FISH_PULAU_2 = [
    // --- EXTINCT ---
    { name: "Foamrunner", tier: "Extinct", img: null },
    { name: "Fogstripe", tier: "Extinct", img: null },
    { name: "Four Eyes Fish", tier: "Extinct", img: null },
    { name: "French Grunt", tier: "Extinct", img: null },
    { name: "Furnace Leaper", tier: "Extinct", img: null },
    { name: "Gale Snapper", tier: "Extinct", img: null },
    { name: "Giant Moray", tier: "Extinct", img: null },
    { name: "Glade Lurker", tier: "Extinct", img: null },
    { name: "Glimmer Guppy", tier: "Extinct", img: null },
    { name: "Glowfin Skipper", tier: "Extinct", img: null },
    { name: "Great Barracuda", tier: "Extinct", img: null },
    { name: "Gulf Toadfish", tier: "Extinct", img: null },
    { name: "Gust Tail", tier: "Extinct", img: null },
    { name: "Hellmaw Eel", tier: "Extinct", img: null },
    { name: "Hogchoker", tier: "Extinct", img: null },
    { name: "Hollow Snapper", tier: "Extinct", img: null },
    { name: "Horizon Tetra", tier: "Extinct", img: null },
    { name: "Idolfish", tier: "Extinct", img: null },
    { name: "Infernal Halibut School", tier: "Extinct", img: null },
    { name: "Inferno Chaser", tier: "Extinct", img: null },
    { name: "Islandhopper Butterflyfish", tier: "Extinct", img: null },
    { name: "Jungle Phantom", tier: "Extinct", img: null },
    { name: "Knifefish", tier: "Extinct", img: null },
    { name: "Lagoon Dart", tier: "Extinct", img: null },
    { name: "Lagoon Lobster", tier: "Extinct", img: null },
    { name: "Langoustine", tier: "Extinct", img: null },
    { name: "Lantern Snapper", tier: "Extinct", img: null },
    { name: "Lava Bream", tier: "Extinct", img: null },
    { name: "Lobster King", tier: "Extinct", img: null },
    { name: "Lumpclinger", tier: "Extinct", img: null },
    { name: "Magma Pike", tier: "Extinct", img: null },
    // --- LIMITED ---
    { name: "Abyssal Maw", tier: "Limited", img: null },
    { name: "Ancient Algae", tier: "Limited", img: null },
    { name: "Ancient Serpent Skull", tier: "Limited", img: null },
    { name: "Ancient Serpent Spine", tier: "Limited", img: null },
    { name: "Ashcloud Archerfish", tier: "Limited", img: null },
    { name: "Azure Studfish", tier: "Limited", img: null },
    { name: "Candy Cane Carp", tier: "Limited", img: null },
    { name: "Candy Cane Cod", tier: "Limited", img: null },
    { name: "Candy Corn Cod", tier: "Limited", img: null },
    { name: "Ember Catfish", tier: "Limited", img: null },
    { name: "Eonshell", tier: "Limited", img: null },
    { name: "Eternal Frostwhale", tier: "Limited", img: null },
    { name: "Frozen Fangfish", tier: "Limited", img: null },
    { name: "Fruitcake Flounder", tier: "Limited", img: null },
    { name: "Werewolf Walleye", tier: "Limited", img: null },
    { name: "Wraithfin", tier: "Limited", img: null },
    { name: "Wretched Guppy", tier: "Limited", img: null },
    { name: "Zombiefish", tier: "Limited", img: null },
    // --- APEX ---
    { name: "Akkorokamui", tier: "Apex", img: null },
    { name: "Ashclaw", tier: "Apex", img: null },
    { name: "Beluga", tier: "Apex", img: null },
    { name: "Bloop Fish", tier: "Apex", img: null },
    { name: "Charybdis", tier: "Apex", img: null },
    { name: "Lusca", tier: "Apex", img: null },
    { name: "Magician Narwhal", tier: "Apex", img: null },
    { name: "Mosslurker", tier: "Apex", img: null },
    { name: "Narwhal", tier: "Apex", img: null },
    { name: "Skeletal Serpent", tier: "Apex", img: null },
    // --- SPECIAL ---
    { name: "Alien Buddy", tier: "Special", img: null },
    { name: "Comically Ginormous Nico", tier: "Special", img: null },
    { name: "Corrupted Floppy", tier: "Special", img: null },
    { name: "Corrupted Kraken", tier: "Special", img: null },
    { name: "Corrupted Mosslurker", tier: "Special", img: null },
];

module.exports = { FISH_PULAU_2 };
